### ISSUE TITLE
Inconsistent underline in hover state of link that looks like a button 

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/component-library#16]
This is a link that is styled to look like a button.   We have links styled to use text-underline-position: under; but our buttons have it unset.  This means that these kind of buttons have the underline a bit lower than actual buttons. See https://sul-dlss.github.io/component-library/links/ and https://sul-dlss.github.io/component-library/button/
![Screenshot 2024-07-12 at 3 54 16 PM (1)](https://github.com/user-attachments/assets/2de7fc0f-65f5-479d-863c-f98e190f5c37)

**Comment by dbranchini** [comment]
Can we change it so the underline looks more typical of text with an underline - _like this_? Also note, the underline is only on hover and active states, not by default.
