### ISSUE TITLE
Active style (redux)

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/component-library#18]
There has been some discussion about the palette that Stanford has not supporting enough variants of the primary/secondary colors.   We could use something like this (which results in #750000).
```
--bs-btn-active-bg: color-mix(in srgb, var(--stanford-digital-red-dark) 90%, black)
```

**Comment by dbranchini** [comment]
We like this idea for a darker red on the secondary (red) buttons. For the filled buttons, this would be the background color, and for the outline buttons, this would be the color of the text and/or icons. 

Using this same approach for the primary or blue buttons would work too.
