### ISSUE TITLE
Add new alert

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/component-library#27]
In addition to those already in the component library, we added a new Alert style ("Note" with a yellow background).
See [Alert - Figma design](https://www.figma.com/design/K1syTsalaB1nlRftgOi0Pw/DLSS-Components?node-id=0-1&m=dev&focus-id=357-660).

**Comment by jcoyne** [comment]
@alundgard what do we call this one in order to differentiate it from the one with the blue background?  How does one know whether the blue or the yellow background one is appropriate?

**Comment by alundgard** [comment]
@jcoyne We can call the blue alert "Info" and the yellow alert "Note". I updated the Figma.
