### ISSUE TITLE
Add links in alerts

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/component-library#3]

**Comment by dnoneill** [comment]
It looks like the links all match the alert color except for warning. Is this on purpose or is this a mistake?

![Screenshot 2024-06-19 at 11 26 30 AM](https://github.com/sul-dlss/component-library/assets/19173991/e33561a1-e65a-4c3b-83f8-7e87bd196f69)

**Comment by dnoneill** [comment]
Checked, it was on purpose

**Comment by jcoyne** [comment]
Fixed on main
