### ISSUE TITLE
Footer brand hover looks bad

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/component-library#50]
<img width="902" alt="Screenshot 2024-10-31 at 10 18 11 AM" src="https://github.com/user-attachments/assets/552d858b-9b2b-4f68-9882-c90c3212c499">

**Comment by dnoneill** [comment]
This is happening because ```text-underline-position: under```. If we change this it should make it look right.

**Comment by jcoyne** [comment]
On https://library.stanford.edu there is no underline on this link at all.  Should we also remove the underline?

**Comment by astridu** [comment]
Yes, please remove the underline. Thank you!

**Comment by jcoyne** [comment]
Fixed by #53
