### ISSUE TITLE
Small footer adjustments

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/component-library#57]
Follow-up from #56
- In the original design, the footer logo is a bit larger than the header logo. If not too difficult, could we keep logo width at 280px in the header, but bump the logo width to 300px in the footer?
- In the component library implementation, it looks like the footer text is slightly misaligned vertically.
<img width="840" alt="footer text alignment" src="https://github.com/user-attachments/assets/12ed67fc-571b-4b8a-a2fe-f30526922521">

**Comment by jcoyne** [comment]
@alundgard The size is no obstacle, but alignment is a challenge. Since this is an image, it's not going to be able to perfectly align the baseline of the text in the image with surrounding text.

**Comment by alundgard** [comment]
@jcoyne I see. If the misalignment is more noticeable and can't be corrected, let's axe the 300 then and stick with 280. Sorry for the back and forth.
